### PR TITLE
unify all DIscrete DS

### LINKED ISSUE #17: Proposal: don't re-compute the vector field and map twice when using ForwardDiff
Reading how [`ContinuousDS(prob::ODEProblem)` w/o Jacobian](https://github.com/JuliaDynamics/DynamicalSystemsBase.jl/blob/6a2698981f621b28ba4be0fe4aa4fa08e669ceb5/src/continuous.jl#L110):
```julia
# Constructors without Jacobian:
function ContinuousDS(prob::ODEProblem)
    state = prob.u0
    eom! = prob.f

    D = length(state); T = eltype(state)
    du = copy(state)
    J = zeros(T, D, D)

    jeom! = (du, u) -> eom!(0, u, du)
    jcf = ForwardDiff.JacobianConfig(jeom!, du, state)
    ForwardDiff_jacob! = (t, u, J) -> ForwardDiff.jacobian!(
    J, jeom!, du, u, jcf)
    ForwardDiff_jacob!(0, state, J)

    return ContinuousDS(prob, ForwardDiff_jacob!, J)
end
```
and [`variational_integrator`](https://github.com/JuliaDynamics/DynamicalSystemsBase.jl/blob/6a2698981f621b28ba4be0fe4aa4fa08e669ceb5/src/continuous.jl#L226):
```julia
function variational_integrator(ds::ContinuousDS, k::Int, T,
    S::AbstractMatrix; diff_eq_kwargs = DEFAULT_DIFFEQ_KWARGS)

    f! = ds.prob.f
    jac! = ds.jacob!
    J = ds.J
    # ... chop ....
    veom! = (t, u, du) -> begin
        us = view(u, :, 1)
        f!(t, us, view(du, :, 1))
        jac!(t, us, J)
        A_mul_B!(view(du, :, 2:k+1), J, view(u, :, 2:k+1))
    end
    # ... chop ....
    return vintegrator
end
```
are defined, I started worry that this implementation may be inefficient, since you call `eom!` (`prob.f`) twice.  Discrete system also has the same problem.  I haven't done any benchmark on this, though.

Here's an implementation for not calling `eom!` twice (as you know :wink: ):
https://gist.github.com/tkf/014787f386e99b7b8b42683cfbd8da01#file-lyapunovexponentswithforwarddiff-jl-L27

The implementation itself is not hard. The main problem is that you need to change the API. That is to say, you need to store the pair `eom!` and (say) "`eom_and_jacob!`" rather than  `eom!` and `jacob!`.  Of course, it is easy to make a backward-compatible layer by calling `eom!` and `jacob!` from the default "`eom_and_jacob!`".  This also helps user to provide a highly efficient implementation.

(A bit tangential notes: I know that the name `eom_and_jacob!` is not cool. Not sure what's the best name.  `tangent_dynamics!`? `coeom!` (co-eom)? `teom!` (tangent-eom)?  `veom!` (variational-)?  `peom!` (paired-)?)

I can do the fix but I thought I'd ask you first, since this is going to change the API (and there is a chance that you have done benchmarks and know that the performance benefit is negligible).

### LINKED ISSUE #21: Overhaul DiscreteDS and BigDiscreteDS and make them one?
Can we do something similar as with #20 and also type-parameterize `DiscreteDS` and `BigDiscreteDS` and make the method parameter be in-place/out of place, and only have a single struct?

### LINKED ISSUE #22: For discrete systems make Jacobian closure over entire system
Implement what is discussed here: https://github.com/JuliaDiff/ForwardDiff.jl/issues/296

### PR DESCRIPTION
**Pull request by Datseris**
Closes #22, closes #21, closes #17

### CODE REVIEW

**Comment by Datseris** [comment]
Please see the file `new_discrete.jl` and give feedback!

**Comment by Datseris** [comment]
@tkf this goes very well with your idea to define a global `eom(u, ds)` function and similar.

**Comment by Datseris** [comment]
@tkf I am merging this now. Can you be kind to checkout master branch and simply read the docs and fundamental types and see if it is nice and usable for other packages?

High level API: `DiscreteDynamicalSystem`, `evolve` and `evolve!` and `trajectory`.

Low level API: `DiscreteProblem`, `jacobian`, `TangentEvolver`, `ParallelEvolver` and their accompanying `evolve!` methods.

For ChaosTools this is amazing, it simplifies the code, and allows to compute `k` lyapunovs instead of all, as well as have a step for the QR, (to be done every `N` steps instead of every 1).

As you suggested ChaosTools will also be reworked to use only `evolve`, and not directly the fields of basic types.

Merging this will close #17 and I will then open a new issue for it, with a clear plan of implementation.

**Comment by tkf** [comment]
@Datseris From a quick look, my comment on https://github.com/JuliaDynamics/DynamicalSystemsBase.jl/issues/21#issuecomment-363644947 still applies.  See also the new comment https://github.com/JuliaDynamics/DynamicalSystemsBase.jl/issues/21#issuecomment-363996568

**Pull request merged**
