### PR TITLE
Using the "uncoupled" Kuramoto version to improve speed.

### PR DESCRIPTION
**Pull request by awage**
This trick that uses the mean field allows to skip a lot of sums: 

```
N = 400
ω = range(-10,10,length = N)
kn = Systems.kuramoto(N; K = 0.1, ω = ω)
T = 40
# PR version
@btime t1 = trajectory(kn, T)
24.202 ms (32202 allocations: 41.37 MiB)

# REP vesion
@btime t1 = trajectory(kn, T)
928.680 ms (31661 allocations: 38.01 MiB)

```

### CODE REVIEW

**Comment by Datseris** [comment]
@awage this PR actually broke things. 
```
julia> Systems.kuramoto()
ERROR: MethodError: no method matching exp(::Vector{Complex{ForwardDiff.Dual{ForwardDiff.Tag{DynamicalSystemsBase.var"#5#11"{typeof(DynamicalSystemsBase.Systems.kuramoto_f), DynamicalSystemsBase.Systems.KuramotoParams{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}}, Float64}, Float64}, Float64, 9}}})
Closest candidates are:
  exp(::Union{Float16, Float32, Float64}) at C:\Users\datse\AppData\Local\Programs\Julia-1.7.0\share\julia\base\special\exp.jl:296
  exp(::StridedMatrix{var"#s859"} where var"#s859"<:Union{Float32, Float64, ComplexF32, ComplexF64}) at C:\Users\datse\AppData\Local\Programs\Julia-1.7.0\share\julia\stdlib\v1.7\LinearAlgebra\src\dense.jl:560
  exp(::StridedMatrix{var"#s859"} where var"#s859"<:Union{Integer, Complex{<:Integer}}) at C:\Users\datse\AppData\Local\Programs\Julia-1.7.0\share\julia\stdlib\v1.7\LinearAlgebra\src\dense.jl:561     
  ...
Stacktrace:
  [1] kuramoto_f(du::Vector{ForwardDiff.Dual{ForwardDiff.Tag{DynamicalSystemsBase.var"#5#11"{typeof(DynamicalSystemsBase.Systems.kuramoto_f
```
I'm wondering how you were able to initialize the system. We need an explicit Jacobian because ForwardDiff cannot play with imaginary numbers. It's the same problem you had when you were doing this Newton's method system.

**Comment by Datseris** [comment]
I've added a "dummy" jacobian to see if that was the problem. It wasn't. Not even standard trajectory works in Julia 1.7:

```
julia> ds = Systems.kuramoto()
25-dimensional continuous dynamical system
 state:       [0.0, 0.261799, 0.523599, 0.785398, 1.0472, …, 5.49779, 5.75959, 6.02139, 6.28319]    
 rule f:      kuramoto_f
 in-place?    true
 jacobian:    #79
 parameters:  KuramotoParams{Float64, StepRangeLen{Float64, TwicePrecision{Float64}, TwicePrecision{Float64}, Int64}}(0.3, -1.0:0.08333333333333333:1.0)

julia> trajectory(ds, 100)
ERROR: MethodError: no method matching exp(::Vector{ComplexF64})
Closest candidates are:
  exp(::Union{Float16, Float32, Float64}) at C:\Users\datse\AppData\Local\Programs\Julia-1.7.0\share\julia\base\special\exp.jl:296
  exp(::StridedMatrix{var"#s859"} where var"#s859"<:Union{Float32, Float64, ComplexF32, ComplexF64}) at C:\Users\datse\AppData\Local\Programs\Julia-1.7.0\share\julia\stdlib\v1.7\LinearAlgebra\src\dense.jl:560
  exp(::StridedMatrix{var"#s859"} where var"#s859"<:Union{Integer, Complex{<:Integer}}) at C:\Users\datse\AppData\Local\Programs\Julia-1.7.0\share\julia\stdlib\v1.7\LinearAlgebra\src\dense.jl:561     
  ...
```

how did it pass for you I don't know.

**Comment by Datseris** [comment]
I've fixed it now on master.

**Comment by awage** [comment]
Weird! I am still on Julia 1.6.3. and it didn't cause any problems.

**Comment by awage** [comment]
I have double checked this PR and probably it was a out of sync git repository. There was another small problem in the equations, I will fix it. 

Checking the benchmarks I have found some very strange problem: 

```
using DifferentialEquations
using DynamicalSystems
using BenchmarkTools

function kuramoto_f!(du, u, p, t)
    ω = p[2]; K = p[1]
    D = length(u)
    z = mean(exp.(im .* u))
    θ = angle(z)
    mf = abs(z)
    @inbounds for i in 1:D
        du[i] = ω[i] + K*mf*sin(θ - u[i])
    end
    return
end

D = 10; K = 3.3; ω = range(-1, 1; length = D); u0 = rand(D)
prob = ODEProblem(kuramoto_f!, u0, [0 200], [K, ω])
@btime sol1 = solve(prob, Tsit5());

ds = Systems.kuramoto(D; K = K, ω = ω)
@btime sol2 = trajectory(ds, 200, u0, diffeq = (;alg = Tsit5()))
```

Results are: 
DifferentialEquations.jl 
1.869 ms (72985 allocations: 1.61 MiB)

DynamicalSystems.jl
14.635 ms (240978 allocations: 21.95 MiB)

These are the same equations but there is a big difference between solvers. What is going on?

**Pull request merged**
