### PR TITLE
add functions to output derivatives

### PR DESCRIPTION
**Pull request by YiboXia94**
add following functions to output derivatives at curent time (refer to ```DiffEqBase.get_du```):

```current_du(ds::DynamicalSystem)```;
```current_du!(out, ds::DynamicalSystem)```.

### CODE REVIEW

**Comment by Datseris** [comment]
(also, you need to add tests for this)

**Comment by YiboXia94** [comment]
sorry... I am really a starter at this.

> We have two options

I would make both functions according to your instructions and we shall see which one is better:)
I would also add tests, but need some time.

**Comment by Datseris** [comment]
Be careful, because the second suggestion requires a lot of code; you'd need to write this for all systems which can be overwhelming for a beginner, and perhaps not really worth it. 

I think the simplest for you is to just rename your current function and only make it work with `CoupledODEs`.

**Comment by Datseris** [comment]
bump here.

**Comment by Datseris** [comment]
I am closing this as stale.

**Pull request closed without merging**
