### PR TITLE
add coupled logistic maps

### PR DESCRIPTION
**Pull request by Datseris**
@awage are the equations correct? I tried to generalize your D=3 case to work for any D, but I think I didn't do it properly. What's the generalized version, if any, that gives us what we want for D=4?

It doesn't matter whether the system is published or not yet, because it will be published with our paper, and so it will be "published" afterwards!

### CODE REVIEW

**Comment by awage** [comment]
It is already published for D=2 and a different coupling:  https://doi.org/10.1016/S0960-0779(02)00171-6

At first I made a mistake with the sign of the parameter k but it was a lucky error since the behavior was so much interesting.

You can verify Fig. 6 (c) of the paper for D=2 and k=-0.08 (k should be negative in the code while it is positive in the paper, maybe you want to change this for replication purposes).

**Comment by Datseris** [comment]
yeah i was thinking we could make a _generalized_ version where one can choose how many logistic maps to couple. The problem is I fear that the system you've shared with me is really sensitive to the somewhat arbitrary choice of whether to do (x^2 - y^2) or the other way around

**Comment by awage** [comment]
This is a strange coupling, usually it is linear. For this coupling (xn² - yn²) it will blow up quickly. But we have a interesting case for weak coupling k as long as D is not too high. .

**Comment by Datseris** [comment]
I think it's fine like this.

**Pull request merged**
