### PR TITLE
Allow keyword propagation in trajectory

### PR DESCRIPTION
**Pull request by awage**
The change is needed to avoid an error caused by the `AttractorsViaFeaturizing` method. When the dynamical system is a strob map or a projected system the method `trajectory` throws an error since the `diffeq` keyword is not included in the list.

### CODE REVIEW

**Comment by Datseris** [comment]
Wait, the `trajectory` function should have the keyword propagation into nowhere, not the lower level methods. These should be clean.

**Comment by awage** [comment]
The problem comes from these lines: 

```julia
function trajectory(integ, args...; kwargs...)
    if isdiscretetime(integ)
        return trajectory_discrete(integ, args...; kwargs...)
    else
        return trajectory_continuous(integ, args...; kwargs...)
    end
end
```

The `diffeq` is propagated and cause an error on the lower level methods.

**Comment by Datseris** [comment]
Oh, this is a really easy fix. Add `diffeq = NamedTuple()` in the first line, and propagate tihs only in the `_continuous` clause.

**Comment by Datseris** [comment]
@awage I don;t understand. I am confused here. I didn't have problems with `diffeq` propagation before. Can you please tell me what is the problem exactly, and then I'll fix it.

**Comment by awage** [comment]
I was wondering if this PR still makes sense. The keyword propagation error came in the file `attractor_mapping_featurizing.jl`:

```julia
function extract_features(mapper::AttractorsViaFeaturizing, u0::AbstractVector{<:Real})
    A = trajectory(mapper.ds, mapper.total, u0;
            Ttr = mapper.Ttr, Δt = mapper.Δt, diffeq = mapper.diffeq)
    t = (mapper.Ttr):(mapper.Δt):(mapper.total+mapper.Ttr)
    feature = mapper.featurizer(A, t)
    return feature
end

```

This function propagated the `diffeq` keyword and it raised an error for `PoincareMap` and `ProjectedIntegrator`.

**Pull request merged**
