### PR TITLE
Making autodiff Jacobian reusable

### PR DESCRIPTION
**Pull request by JonasKoziorek**
I have separated the `ForwardDiff.jl` jacobian from the `tangent_rule`. This way we can reuse this in `PeriodicOrbits.jl`. 

If you find everything ok, I will modify the docstrings.

### CODE REVIEW

**Comment by JonasKoziorek** [comment]
I am unsure about the `Jacobianconfiguration`. Is this ok?

https://github.com/JuliaDynamics/DynamicalSystemsBase.jl/blob/82b29159d14cec249df46bc14749b7651a92383d/src/core_systems/jacobian.jl#L9-L24

Especially line 17. I suppose that `du` is there just as a container.

**Review by Datseris — APPROVED** [review]
yeah this seems fine to me. In the future don't wait for a review to add the documentation. **The documentation is the most important part and is what you should be writing first anyways!**

**Comment by JonasKoziorek** [comment]
Please review if it position of the `jacobian.jl` file and the docs position is ok.

**Review by Datseris — APPROVED** [review]
Perfect. Don't forget to increment minor version in Project.toml and add a changelog entry.

**Comment by Datseris** [comment]
ah, also tests fail. Can you check that please?

**Comment by JonasKoziorek** [comment]
The test fails for `successful_step` of `ParallelDynamicalSystem`. It is not related to the changed in this PR. I will try to fix it.

**Comment by Datseris** [comment]
If you want to fix it, thanks, as it is not related to your GSOC, but please do so in another PR!

**Pull request merged**
