### PR TITLE
Added Cao's method

### PR DESCRIPTION
**Pull request by JonasIsensee**
Basic Implementation only.

Docs and Tests are still missing but coming in soon (hopefully)

A wrapper function 
```julia
estimate_dimension(timeseries , τ) 
```
could also be helpful.

### CODE REVIEW

**Comment by Datseris** [comment]
Amazingu.

`estimate_dimension(timeseries , τ, Ds = 1:6) ` is necessary, yeah (with default values of dimensions to search at). You can look into the code I have written to automatically deduce the fractal dimensions of a dataset. There I find "local constant linear slopes" and get the largest.

You can use a similar approach to see when the `E1` stops increasing significantly.

Important change:
1. Having functions name after a single letter is a not good approach. In fact it is prone to lead to huge breakages. What if I want to call this function in another function and I have already allocated another variable named `E`? Which sounds something completely normal? You can rename `E` to `average_a`. Then, we know that `E1` is the "indicator for the correct dimension" and thus you can rename it to `dimension_indicator`. Same for `E2` to be `stochastic_indicator`.

Feel free to suggest different and better names.

**Of course, in the source code there will be a comment line that says "this function represents equation 1# and whatever**

Performance comments:

2. Kristoffer answered here: https://github.com/KristofferC/NearestNeighbors.jl/issues/63#issuecomment-371457281 I think this method can be highly optimized by first creating a vector of all nearest neighbors and then doing the computation this way.
3. A second Reconstruction may not be really necessary. We can define a clever function that makes the ratio of equation (1) in the Cao paper, and cleverly use the timeseries `s` and never create the `d+1` reconstruction. So the nominator is computed via a loop over `d+1`, while the denominator is computed from the timeseries. One has to benchmark the two aproaches and see which one is faster, becayse static arrays are also very optimized.

**Comment by Datseris** [comment]
Point 3. of my comment is for a later date. Not crucial now.

**Comment by JonasIsensee** [comment]
Method works for low dimensional systems. Have not been getting expected results for lorenz96 system. See picture below.


caolorenz96

Tests fail, because my test uses ChaosTools which is not in `REQUIRE`. Should I add it or do we move the function?

**Comment by Datseris** [comment]
The plan is to *not* have `ChaosTools` in the require of this package.

if some method is used for both packages (and is of course actually important) we can move it to base.

For tests, you can create a second require file inside the test folder (just did it now) which says what packages you need only for testing.

**Comment by Datseris** [comment]
@JonasIsensee sorry, my mistake. We cannot have ChaosTool in the require here, since ChaosTools itself requires dynamicalsystemsbase. 

A better approach is to just copy paste the function inside the test script.

**Comment by JonasIsensee** [comment]
Ready for review.

**Pull request merged**
